### PR TITLE
Fix builds on BSD platforms by invoking "gmake", not "make".

### PR DESCRIPTION
**Pull request by ke6jjj**

### CODE REVIEW

**Comment by madninja** [comment]
Did you do another wonky rebase @ke6jjj ?

**Comment by ke6jjj** [comment]
Oof. No, I didn't do a rebase, @madninja, but I did nearly the same thing: I created my branch on the cloned repository directly in the miner `_build/...` subdirectory. It clearly wasn't branched off of `master` but off of .. aha, `origin/andymck/grpc-state-channel-apis-v2`, since that's what `rebar.lock` had configured. Perhaps I should have made the PR into _that_ branch, not master.

**Comment by ke6jjj** [comment]
Does it look better now, @madninja? Or would you like it to be properly rebased so that it can be pulled into `master`?

**Comment by madninja** [comment]
> Does it look better now, @madninja? Or would you like it to be properly rebased so that it can be pulled into `master`?

I'll let @andymck decide that

**Comment by andymck** [comment]
@ke6jjj can you please recut this off master and we will get it merged.

**Pull request closed without merging**
